### ISSUE TITLE
can't make rdp because it's just stuck in the "checking" section of the terminal, even though the rdp was successfully created, but it doesn't have internet access

### ISSUE THREAD

**Issue by Nancysavvv** [kmille36/Windows-11-VPS#1]
can't make rdp because it's just stuck in the "checking" section of the terminal, even though the rdp was successfully created, but it doesn't have internet access

please fix this

**Comment by kmille36** [comment]
Sorry for the late reply, but the problem seems to have already been fixed.

**Comment by discordgladiator2** [comment]
it isnt fixed yet , same happening
