### ISSUE TITLE
No longer works, infinite wait, nothing happens.

### ISSUE THREAD

**Issue by Jakeeeeeeee** [kmille36/Windows-11-VPS#106]
https://i.gyazo.com/775f206403f3de737dab3190e17cc45a.png
result of almost an hour of waiting
https://i.gyazo.com/40b8fe98edb90032a0aaf75da7dc8983.png

**Comment by kmille36** [comment]
Read optional ???

**Comment by kmille36** [comment]
Scroll down and read it, it common problem
