### ISSUE TITLE
Closed-sourced binary

### ISSUE THREAD

**Issue by SoftwareRat** [kmille36/Windows-11-VPS#11]

**Comment by SoftwareRat** [comment]
Please provide the source code of your code, else I cannot be sure what it does

**Comment by kmille36** [comment]
Hi

**Comment by kmille36** [comment]
My code clean, no malware or keylog. u can use malwarebytes to perform full system scan.

**Comment by tauoverpi** [comment]
Why are the two `.sh` "scripts" obfuscated? Shouldn't they be plain text files? The contents of the scripts cannot be trusted in their given form as you're using the same method as malware to hide what your scripts contain.

**Comment by kmille36** [comment]
Use this to check my is.gd shorten link: http://checkshorturl.com/

**Comment by kmille36** [comment]
Im encrypted my source code for private method. I dont want use can see and edited it.

**Comment by tauoverpi** [comment]
Then this code cannot be trusted.

**Comment by kmille36** [comment]
Hmm, im sure it no virus.

**Comment by MCPEngu** [comment]
Your scripts cannot be trusted if it's doesn't open source.

**Comment by tauoverpi** [comment]
Turns out it is open source :D

https://raw.githubusercontent.com/kmille36/thuonghai/master/katacoda/AZ/az-create.sh

```
$ ./start-create-vm.sh
Script by fb.com/thuong.hai.581
 curl -s -L -k https://raw.githubusercontent.com/kmille36/thuonghai/master/katacoda/AZ/az-create.sh
 bash /tmp/tmp.foqazV9IXE/az-create.sh

**Comment by kmille36** [comment]
OK.

**Comment by kmille36** [comment]
If anyone find my script contain malware or something similar contact me for reward. XD (im sure about this).

**Comment by kmille36** [comment]
> Hóa ra đó là "nguồn mở" :D
> 
> https://raw.githubusercontent.com/kmille36/thuonghai/master/katacoda/AZ/az-create.sh
> 
> ```
> $ ./start-create-vm.sh
> Script by fb.com/thuong.hai.581
>  curl -s -L -k https://raw.githubusercontent.com/kmille36/thuonghai/master/katacoda/AZ/az-create.sh
>  bash /tmp/tmp.foqazV9IXE/az-create.sh
> ```

Oh no XD. And no untrusted code found, right?

**Comment by tauoverpi** [comment]
I don't see why you need to obfuscate it in the first place for something which just downloads a script from another public repository. Feels unnecessary.

**Comment by kmille36** [comment]
Hi @SoftwareRat  dm me in discord @thuonghai2711#7681 for future questio about script.
