### ISSUE TITLE
Possible to add windows 7???

### ISSUE THREAD

**Issue by sadiPod** [kmille36/Windows-11-VPS#12]
hi it is possible to add windows 7 i see windows 7 in market place
![Screenshot 2022-04-27 145725](https://user-images.githubusercontent.com/83070165/165461461-5d9ae817-f1ac-4613-9c48-8e7cc46aa224.png)
![Untitled](https://user-images.githubusercontent.com/83070165/165461517-1993c322-a1e2-4a76-b56f-2c828e91d060.png)

**Comment by hoangdevpython** [comment]
how to reg vps macos not lunix on qemu

**Comment by kmille36** [comment]
Lul but windows 7 missing some newest library that need on my script.

**Comment by kmille36** [comment]
Hi, sorry but too hard to make my script working on windows 7, therefore i am closing this issue.
