### ISSUE TITLE
Server Not Working

### ISSUE THREAD

**Issue by ADYZM** [kmille36/Windows-11-VPS#14]
is.gd server is not working, 502 issue. Thanks

**Comment by kmille36** [comment]
It due is.gd shorten link. Solved by replace direct link into gtihub file in my repo.

**Comment by kmille36** [comment]
<img width="766" alt="image" src="https://user-images.githubusercontent.com/58414694/165747553-5a73c223-a5e0-483e-a58e-b8d43ff1adc1.png">
Click on it, and get raw link

**Comment by ADYZM** [comment]
thanks dude.. good job..

**Comment by Ashka0131** [comment]
and what to do with these files?

**Comment by Ashka0131** [comment]
kmille36

**Comment by ADYZM** [comment]
> and what to do with these files?

download that than upload on the file sharing, then download again on azure

**Comment by hoangdevpython** [comment]
Good bro

Vào 20:19, T.5, 28 Th4, 2022 ADYZM ***@***.***> đã viết:

**Comment by muhtesem0** [comment]
Use this:
curl -skLO bit.do/azurewinvmplus ; chmod +x azurewinvmplus ; ./azurewinvmplus
