### ISSUE TITLE
CHECKING FOR 10 MINUTES WAIT

### ISSUE THREAD

**Issue by Ashka0131** [kmille36/Windows-11-VPS#18]

**Comment by kmille36** [comment]
<img width="522" alt="image" src="https://user-images.githubusercontent.com/58414694/165931759-6fc00d30-d81a-47af-acba-3a5bcf532862.png">
Read

**Comment by kmille36** [comment]
> sử dụng windows 2022 visual studio 2 cpu 8 gb ram và không hoạt động

It common problem. Just change location or wait few hours then try again. Cheers!
