### ISSUE TITLE
24/7 Service

### ISSUE THREAD

**Issue by chiragnahata** [kmille36/Windows-11-VPS#20]
Will this be on for 24/7 ?

**Comment by kmille36** [comment]
No.

**Comment by chiragnahata** [comment]
Is there any way like bot or automation for free that would automatically
generate the windows cloud pc after every 4 hours and automatically add the
credentials to my Microsoft Remote Desktop.

Do the IP address always remains the same or it changes ?

At once can I get acess to all the versions of windows if i use different
accounts ? Will Microsoft 365 accounts will work to access these ?

How to acess Linux distributions GUI like Ubuntu and Kali Linux ?

Chirag Nahata

**Comment by kmille36** [comment]
Sorry but Linux i preferred u using Google Cloud Shell here: 
- Ubuntu: https://github.com/kmille36/Docker-Ubuntu-Desktop-NoMachine
- Kali: https://github.com/kmille36/Docker-Kali-Desktop-NoMachine
Currently impossible to make Linux, my script support only for windows.

**Comment by kmille36** [comment]
<img width="602" alt="image" src="https://user-images.githubusercontent.com/58414694/166102416-7afce72a-2b6c-416e-9526-74752bdf22cb.png">
Download Remote Desktop from Microsoft Store
IP different each VM.

**Comment by kmille36** [comment]
Will Microsoft 365 accounts will work to access these ? Yes but same as normal account, just for activate sandbox.
