### ISSUE TITLE
Is it private

### ISSUE THREAD

**Issue by chiragnahata** [kmille36/Windows-11-VPS#22]
Are the servers private ?

**Comment by kmille36** [comment]
Yes all server are privated and your network connection encrypted both client and server using HTTPS connection (it use my own method to bypass network restrict by MS Learn) . You can change new password for RDP after connected.

**Comment by chiragnahata** [comment]
After 4 hours no one else would be able to across my files if i left any by
mistake

Chirag Nahata

**Comment by kmille36** [comment]
Yes. VM destroyed aftet 4H.

**Comment by blawte** [comment]
How do I get rid of slow rdp computer and connection problems
