### ISSUE TITLE
Limited Data

### ISSUE THREAD

**Issue by MarleneShannon** [kmille36/Windows-11-VPS#24]
at first i must thank you for not just offering this rdp which helps me a lot in my work but for keep updating it and very keen to keep it useful/usable for a lot of kind purposes.

my only problem that it offers very limited internet quota, all i just need is to extend quota from 3 or 4 giga to be 10 giga which will help me in my works ( mainly downloads stuff and media from different sites and upload it ALL  on   Google drive)

if you can help me i would be much appreciated.
Thanks in advance   
 in case you would contact me privately I'll be so glade to receive your emails on 
MARSHANNON845@STUDENT.CITRUSCOLLEGE.EDU

**Comment by kmille36** [comment]
Can you use Linux OS instead?

**Comment by thegoodkid068** [comment]
> at first i must thank you for not just offering this rdp which helps me a lot in my work but for keep updating it and very keen to keep it useful/usable for a lot of kind purposes.
> 
> my only problem that it offers very limited internet quota, all i just need is to extend quota from 3 or 4 giga to be 10 giga which will help me in my works ( mainly downloads stuff and media from different sites and upload it ALL on Google drive)
> 
> if you can help me i would be much appreciated. Thanks in advance in case you would contact me privately I'll be so glade to receive your emails on [MARSHANNON845@STUDENT.CITRUSCOLLEGE.EDU](mailto:MARSHANNON845@STUDENT.CITRUSCOLLEGE.EDU)

Can you refer me to how you created your edu mail

**Comment by nityanand86876** [comment]
> > at first i must thank you for not just offering this rdp which helps me a lot in my work but for keep updating it and very keen to keep it useful/usable for a lot of kind purposes.
> > my only problem that it offers very limited internet quota, all i just need is to extend quota from 3 or 4 giga to be 10 giga which will help me in my works ( mainly downloads stuff and media from different sites and upload it ALL on Google drive)
> > if you can help me i would be much appreciated. Thanks in advance in case you would contact me privately I'll be so glade to receive your emails on [MARSHANNON845@STUDENT.CITRUSCOLLEGE.EDU](mailto:MARSHANNON845@STUDENT.CITRUSCOLLEGE.EDU)
> 
> Can you refer me to how you created your edu mail

i also want to know that

**Comment by MarleneShannon** [comment]
> Can you use Linux OS instead?

sorry for my late reply

Has Linux OS available a storage like windows to store my downloaded files?
if yes , please let me know how can i use it?

**Comment by kmille36** [comment]
Colab RDP
