### ISSUE TITLE
Stuck on checking .....

### ISSUE THREAD

**Issue by Westlife6666** [kmille36/Windows-11-VPS#25]
Good day Kmille36,

First would like to thank you for your efforts that we all appreciate it

Also I have always issue that continues ... I create first VM no issue but when I try to creat another VM after 4h it always stuck on checking ... see screenshot

https://prnt.sc/PH0i6FGvZ2X4

And I keep refresh the page and delete VM and re create new one .. also tried to change Region and windows type but still stcuk on checking .. it works only next day

**Comment by kmille36** [comment]
If it not work try change to another server .

**Comment by kmille36** [comment]
<img width="547" alt="image" src="https://user-images.githubusercontent.com/58414694/166919901-7fa1c59d-ac93-498b-9631-820c7c6f3068.png">
