### ISSUE TITLE
internet disconnected after few minutes 

### ISSUE THREAD

**Issue by titosalah** [kmille36/Windows-11-VPS#26]
**hi there 
why internet disconnected  from server after few minutes 
and this message keep pop up click ok don't fix the problem** 
![2022-05-06_075121](https://user-images.githubusercontent.com/2828165/167240961-4dbff61b-a73f-4ebe-bd2e-a1bf3949f2bf.jpg)

**if i restart server internet back again but on for few minutes**

**Comment by kmille36** [comment]
Location?

**Comment by kmille36** [comment]
And what application u intall on RDP?

**Comment by titosalah** [comment]
location us and HK same problem ... only use chrome

**Comment by kmille36** [comment]
This due you download large files or you using some software conflig with it.
