### ISSUE TITLE
Can not connect to internet

### ISSUE THREAD

**Issue by rockydares** [kmille36/Windows-11-VPS#28]
You script successfully creates VM then it just keeps on checking for 2 mintutes and nevers completes the process. Tried to re-run the script multiple times but same. RDP opens but I can't open any domains except for being search engine. Tried manually creating outbound rules but no luck. 

Would you tell us how to make outbound rules settings so that we can access internet after creating VM?

**Comment by kmille36** [comment]
If your server your choice not work, switch to another, it should work.
<img width="800" alt="image" src="https://user-images.githubusercontent.com/58414694/167401489-2a520bde-554e-49b6-83d3-0a63232686a7.png">

**Comment by kmille36** [comment]
> Would you tell us how to make outbound rules settings so that we can access internet after creating VM?

No, u cant do that. U must wait until script finished before you can use internet.

**Comment by rockydares** [comment]
Ok, I'm creating VM using this ```https://docs.microsoft.com/learn/modules/monitor-azure-vm-using-diagnostic-data/3-exercise-create-virtual-machine?activate-azure-sandbox=true``` link and using 'azurewin11vm' script. 
Then I select any region and Option 1 for standard vm and I select windows 11 or 11 Pro. After that the script runs and creates VM and shows IP address and keeps on checking (for more than 1 hour) but 80% of the time script doesn't finish. It keeps on checking. The outbound internet script doesn't run or finishes. I can log into VM but I can't use internet on it.

**Comment by kmille36** [comment]
which region u choose?
