### ISSUE TITLE
how do you get internet access?

### ISSUE THREAD

**Issue by nityanand86876** [kmille36/Windows-11-VPS#30]
i want to boot up a vm with ubuntu with internet access for using snap store because snap store requires outbount internet access.
please help me

**Comment by kmille36** [comment]
Hi, will support soon, but not yet available. I cant share u source code.

**Comment by nityanand86876** [comment]
ok

**Comment by nityanand86876** [comment]
but please as soon as possible

**Comment by kmille36** [comment]
Ubuntu there a lot of site: google colab, google cloud shel,... why u want azure sandbox?

**Comment by kmille36** [comment]
I need a reason, so im will bring it to azure sandbox for linux support.

**Comment by nityanand86876** [comment]
google cloud shell is limited and google colab is also limited such as 1 hour so i want azure sandbox which gives somewhat 10 sandbox per day which means 40 hours per day roughly so i want that

**Comment by nityanand86876** [comment]
and one other reason is external ip address where we can share big files such as in a friends group

**Comment by nityanand86876** [comment]
and can do much more

**Comment by kmille36** [comment]
OK

**Comment by kmille36** [comment]
How can i contact with you, facebook,discord... or gmail ? Let me know.

**Comment by nityanand86876** [comment]
you can contact me on nntjkl@gmail.com

**Comment by nityanand86876** [comment]
did you made ubuntu script

**Comment by nityanand86876** [comment]
sorry for not getting on github for many days

**Comment by nityanand86876** [comment]
now i only need ubuntu and dont need windows vps because now i have 100 mbps of interet which is greater than what is provided in vps

**Comment by kmille36** [comment]
No Ubuntu
