### ISSUE TITLE
Add a central India location?  

### ISSUE THREAD

**Issue by nityanand86876** [kmille36/Windows-11-VPS#31]
Add more locations for less ping and network stability in my region
My region - India

**Comment by nityanand86876** [comment]
At first do #30  issue and then do This issue

**Comment by kmille36** [comment]
Hi

**Comment by kmille36** [comment]
I added South India into script, hope u like it.

**Comment by kmille36** [comment]
![image](https://user-images.githubusercontent.com/58414694/169102815-4949df03-caf8-4d25-b621-5fdeb047f9e0.png)

Proof !
