### ISSUE TITLE
stuck at checking...

### ISSUE THREAD

**Issue by robin98** [kmille36/Windows-11-VPS#33]
Hi,
just for the first time(for each Microsoft account) it works fine, but at the second try, it failing over and over and stuck at "checking..." after giving me the IP address.
When I connect to that IP, the virtual server have no access to the Internet.
I tried OPTIONAL link(2H), and it's still not working for me.
Also I tried removing old VM manually from the azure portal, also did not work.

**Comment by robin98** [comment]
UPDATE: I found this at "Activity Log" at portal.azure.com:

> Update hosting plan
Unauthorized
This subscription has reached the limit of 1 Free Linux app service plan(s) it can create in this region. Please choose a different sku or region.

**Comment by kmille36** [comment]
> Hi, just for the first time(for each Microsoft account) it works fine, but at the second try, it failing over and over and stuck at "checking..." after giving me the IP address. When I connect to that IP, the virtual server have no access to the Internet. I tried OPTIONAL link(2H), and it's still not working for me. Also I tried removing old VM manually from the azure portal, also did not work.

You dont need delete it manually, press n and script will do it for you.

**Comment by kmille36** [comment]
> UPDATE: I found this at "Activity Log" at portal.azure.com:
> 
> > Update hosting plan
> > Unauthorized
> > This subscription has reached the limit of 1 Free Linux app service plan(s) it can create in this region. Please choose a different sku or region.

Please delete all resource include old web app. Not just VM
