### ISSUE TITLE
Can i use this free vps on macbook laptop

### ISSUE THREAD

**Issue by designstudioom0** [kmille36/Windows-11-VPS#35]
Hello 

Can i install this windows 11 vps on my Mac ?

if i do install it on mac, so is this free vpn still available free

**Comment by kmille36** [comment]
Yes, it cloud VM.

**Comment by awwsssssssss** [comment]
You can dot that with the RDP for Mac

# If You have issue 3 hour to 1 hour please visit this issues
#46
