### ISSUE TITLE
malicious code

### ISSUE THREAD

**Issue by rajkumaricode** [kmille36/Windows-11-VPS#4]
after me and my other 3 friends using your sanbox script, and loging via remote desktop, my local sytem unstable and make lots of problam, why

this is not a giniune work, shame you

**Comment by kmille36** [comment]
You cab read READ-THIS.txt to see what programs this installed

**Comment by kmille36** [comment]
You can use malwarebytes to scan all system if u dont trust my script, and you can manually create VM in azure portal to see what difference. Thanks.

**Comment by kmille36** [comment]
1. Chrome 
2. Chocolatey
And this image come from windows 365, so i already have ms team and office 365 by default.

**Comment by rajkumaricode** [comment]
> Software i'm added.
> 
>     1. Chrome
> 
>     2. Chocolatey
>        And this image come from windows 365, so i already have ms team and office 365 by default.

ok we agree with you, but why system unstable, not only me my friends also, 

sorry for bad language use my last commit, please recheck your script

**Comment by rajkumaricode** [comment]
> > Software i'm added.
> > ```
> > 1. Chrome
> > 
> > 2. Chocolatey
> >    And this image come from windows 365, so i already have ms team and office 365 by default.
> > ```
> 
> ok we agree with you, but why system unstable, not only me my friends also,
> 
> sorry for bad language use my last commit, please recheck your script

using this script via azure sandbox - 
 curl -skLO is.gd/azurewin11vm ; chmod +x azurewin11vm ; ./azurewin11vm

**Comment by kmille36** [comment]
Can u explain more about "system unstable"?  Idk

**Comment by kmille36** [comment]
About VM performance or network?

**Comment by rajkumaricode** [comment]
when me access your scripted remote commection via rdp , after 15- 20 minutes when full load win 11 suddenlly my local pc hang a lot, 

and freeze 5 or more time in 1 hours and my kingston ddr3 4 gb rem crash, this is my case

my friends facing issue with auto file sharing option enebled without any manual action, and currupt some file

**Comment by rajkumaricode** [comment]
> when me access your scripted remote commection via rdp , after 15- 20 minutes when full load win 11 suddenlly my local pc hang a lot,
> 
> and freeze 5 or more time in 1 hours and my kingston ddr3 4 gb rem crash, this is my case
> 
> my friends facing issue with auto file sharing option enebled without any manual action, and currupt some file

my another friend facing MBR curupt error

**Comment by kmille36** [comment]
It remote RDP, it does not harm your PC.

**Comment by kmille36** [comment]
Can you provide me some screenshot for this case?

**Comment by rajkumaricode** [comment]
> It remote RDP, it does not harm your PC.

i agree you, rdp safe compare to vnc and other remaote access tool, but if facing only me any issue , i agree with you but also facing issue my friend, sorry type so fast. so language mistkate,

**Comment by rajkumaricode** [comment]
ok sir, me check again your win 11 rdp, and check if any issue faced me, then contact you, last your work awesome, i have use all your reposetries , no issue i have found, but this rdp crash my ram, anyway i am big fan you, and also follower, soory if you facing any disturbance with myself
