### ISSUE TITLE
Request to support the Chinese version of Windows 11, preferably a pure version without third-party software.

### ISSUE THREAD

**Issue by 95i** [kmille36/Windows-11-VPS#42]
Request to support the Chinese version of Windows 11, preferably a pure version without third-party software.

**Comment by kmille36** [comment]
OK.

**Comment by kmille36** [comment]
Use this site: https://cloudacademy.com/lab/start-your-first-azure-virtual-machine-windows/
After that your can create your own vm without restrictions. Cheers!
