### ISSUE TITLE
New: Bug In Code

### ISSUE THREAD

**Issue by awwsssssssss** [kmille36/Windows-11-VPS#46]
My Computer is Windows 11
i Found a Changed 3 hours to 1 hours + cannot Download
Thanks

**Comment by GaiaWulan** [comment]
I experienced it too

Pada tanggal Jum, 17 Jun 2022 21.59, awwsssssssss ***@***.***>
menulis:

**Comment by kmille36** [comment]
now it 1h

**Comment by GaiaWulan** [comment]
Oooh nooo... 😢
I want to catch up on my youtube channel's showtime
My channel → Intech Game

Pada tanggal Jum, 17 Jun 2022 22.23, Nguyen Thuong Hai <
***@***.***> menulis:

**Comment by kmille36** [comment]
curl -skLO is.gd/azurewinvmplus ; chmod +x azurewinvmplus ; ./azurewinvmplus

**Comment by GaiaWulan** [comment]
Lets get it

Pada tanggal Jum, 17 Jun 2022 22.29, Nguyen Thuong Hai <
***@***.***> menulis:

**Comment by awwsssssssss** [comment]
@kmille36  why timer changed to 1 hour

**Comment by kmille36** [comment]
Due too much people using this.

**Comment by awwsssssssss** [comment]
Issue Close With Good System

**Comment by GaiaWulan** [comment]
Any solution?

Pada tanggal Min, 19 Jun 2022 19.09, Nguyen Thuong Hai <
***@***.***> menulis:

**Comment by GaiaWulan** [comment]
I dont know... me to 😁

Pada tanggal Min, 19 Jun 2022 07.41, awwsssssssss ***@***.***>
menulis:
