### ISSUE TITLE
Why.

### ISSUE THREAD

**Issue by nvx0** [kmille36/Windows-11-VPS#49]
Why not sharing the source code? GitHub has been created to share source code not encrypt it with PGP. I am not here to make an argument but I am very curious how it works. Thanks.

**Comment by nityanand86876** [comment]
https://raw.githubusercontent.com/kmille36/thuonghai/master/katacoda/AZ/az-create.sh
Take this source code

**Comment by kmille36** [comment]
> https://raw.githubusercontent.com/kmille36/thuonghai/master/katacoda/AZ/az-create.sh Take this source code

To prevent abuse, i don't want anyone public my source. Sorry for that.

**Comment by nvx0** [comment]
Explain what is abuse.
