### ISSUE TITLE
please fix my issue

### ISSUE THREAD

**Issue by Ma24wt** [kmille36/Windows-11-VPS#5]
hello , guy please someone help me I just bought a new pc 5-6 days ago. it is having the issue in internet like in azure. he told us how to fix it in azure but this command is not working in my pc it also have windows11 please help me and give me a script so that I can fix this error.

**Comment by kmille36** [comment]
What do you mean?

**Comment by kmille36** [comment]
Your issue not come from azure sandbox?

**Comment by Ma24wt** [comment]
bro please tell me how to increase my pc internet speed

**Comment by kmille36** [comment]
You asking question that not come from my script.
