### ISSUE TITLE
Reinstall Fail when recreate

### ISSUE THREAD

**Issue by KevinNitroG** [kmille36/Windows-11-VPS#51]
Reinstall Fail when recreate VPS on another location with same sandbox.
I have already installed a windows 11 on EU server but I faced the issue that couldn't access google _(youtube, gdrive,...)_. Only bing search was available _(I didn't check more website)_. Then I recreate another win 10 VPS on US server, and I got this error.
 Please check out the logs.

Script by fb.com/thuong.hai.581
Repo: https://github.com/kmille36/Windows-11-VPS
    _     ______   _ ____  _____ 
   / \   |__  / | | |  _ \| ____|
  / _ \    / /| | | | |_) |  _|  
 / ___ \  / /_| |_| |  _ <| |___ 
/_/   \_\/____|\___/|_| \_\_____|
1. Standard_DS2_v2 - 2CPU/7GB - Suitable if you want VM with the highest performance
2. Standard_D2s_v3 - 2CPU/8GB - Slower than DS2_v2 but have nested virtualization
Please select your Azure VM size (type number then press enter):1
OK
⌛  Setting up... Please Wait...
⌛  Checking Previous VM...
You Already Have Running VM...
VirtualMachine    PublicIPAddresses    PrivateIPAddresses
----------------  -------------------  --------------------
Windows-VM-PLUS   ip_(I hid it)_       10.0.0.4
       Do you want to keep current VM?
y: Keep current VM states and output RDP File
n: Delete previous VM then re-create new one
Press [y/n] then enter: n
🖥️  Deleting VM... (about 3m)
Cleaning...(50s)
⌛  Setting up... Please Wait...
⌛  Checking Previous VM...
🖥️  Creating In Process...
{"error":{"code":"InvalidResourceLocation","message":"The resource 'Windows-VM-PLUSVMNic' already exists in location 'westeurope' in resource group 'learn-e7015728-fe0b-4c90-a82f-0453fcde6cc7'. A resource with the same name cannot be created in location 'eastus'. Please select a new resource name."}}
⌛  Wait... (Can take up to 2 minutes)
 Checking .      🌐 

It stucked at Checking for long time. And I gotta have dinner....

**Comment by kmille36** [comment]
Just active new sandbox using OPTIONAL link above, no need to wait if it checking more than 2min.
