### ISSUE TITLE
THE VPS CLOSE AFTER 1H WHY?

### ISSUE THREAD

**Issue by amwzf** [kmille36/Windows-11-VPS#52]
Why The VPS Close After 1H?

**Comment by kmille36** [comment]
What wrong with you?? Are u serious?

**Comment by quan9364** [comment]
So is there any way to solve this problem so as to using 4 hours please? @kmille36 thanks.

**Comment by kmille36** [comment]
I dont know, they changed time to 1H all learn module about creating VM.

**Comment by kmille36** [comment]
@quan9364 If you don't mind, can you try search sandbox higher than 1H  in ms learn site. Thanks.

**Comment by kmille36** [comment]
Hmm.
