### ISSUE TITLE
How do you setup the internet. Please tell me. Don't count it as a issue.

### ISSUE THREAD

**Issue by Souparno10** [kmille36/Windows-11-VPS#54]
How do you setup the internet in the vm. Please tell me how to set it manually. Actually I am learning azure and came around here. Love the hard work BUT please do mention how you did it.

**Comment by quan9364** [comment]
I can't connect to the internet via RDP, even though the system noticed that "The internet access is ready". I am wondering if Azure banned from using this remote RDP.

**Comment by Souparno10** [comment]
I mean that I have access to the Internet. I can search and do things which are stuck to the search engine. I can't go to google.com. I wanted to use the internet to install CLI tools in Visual Studio. If you use the console to run the code given as per as the instructions in the repository then it is working, but if I don't use the console I want to manually how to connect in azure.

**Comment by kmille36** [comment]
Hi, it error or not work some time, please deactived old sandbox using OPTIONAL link, then do again to get fresh VM.
