### ISSUE TITLE
Checking takes forever in Central India

### ISSUE THREAD

**Issue by Souparno10** [kmille36/Windows-11-VPS#55]
In Central India location of the VM, it takes forever. The whole hour goes away while it keeps checking. Rest of the regions are good. Please try to fix it.

**Comment by kmille36** [comment]
This is common issue, unfortunately i cannot fix it, just choose another nearest region like east asia.

**Comment by kmille36** [comment]
Sorry! This location no longer work!! So i'm remove this!
