### ISSUE TITLE
cant use

### ISSUE THREAD

**Issue by wcw1qqw** [kmille36/Windows-11-VPS#56]
curl -skLO bit.do/azurewinvmplus ; chmod +x azurewinvmplus ; ./azurewinvmplus
chmod: cannot access 'azurewinvmplus': No such file or directory
bash: ./azurewinvmplus: No such file or directory

**Comment by BacaninhaGames** [comment]
same here

**Comment by ShivaShirsath** [comment]
```bash
curl -skLO https://github.com/kmille36/Windows-11-VPS/raw/main/start-create-vm.sh ; chmod +x start-create-vm.sh ; ./start-create-vm.sh

```

Follow Please
Thank you 😇

**Comment by THELIGHTSIDE2003** [comment]
same here

**Comment by agrawliabde** [comment]
> Use this code
> 
> This code works in my terminal
> 
> ```shell
> curl -skLO https://github.com/kmille36/Windows-11-VPS/raw/main/start-create-vm.sh ; chmod +x start-create-vm.sh ; ./start-create-vm.sh
> ```
> 
> Follow Please Thank you 😇

can you please give us code for vm plus so we can choose options windows 10 thank you for the first one

**Comment by kmille36** [comment]
It due bit.do website down.

**Comment by kmille36** [comment]
curl -skLO is.gd/azurewinvmplus ; chmod +x azurewinvmplus ; ./azurewinvmplus

**Comment by kmille36** [comment]
Hi, UPDATE readme.md. Thanks for reporting issue.

**Comment by ShivaShirsath** [comment]
> > Use this code
> > This code works in my terminal
> > ```shell
> > curl -skLO https://github.com/kmille36/Windows-11-VPS/raw/main/start-create-vm.sh ; chmod +x start-create-vm.sh ; ./start-create-vm.sh
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Follow Please Thank you 😇
> 
> can you please give us code for vm plus so we can choose options windows 10 thank you for the first one

Yes 

Here it is 

```bash
curl -skLO https://github.com/kmille36/Windows-11-VPS/raw/main/start-create-vm-plus.sh ; chmod +x start-create-vm-plus.sh ; ./start-create-vm-plus.sh

```
