### ISSUE TITLE
Error while creating Windows 10 Pro VPS

### ISSUE THREAD

**Issue by Souparno10** [kmille36/Windows-11-VPS#59]
"Querying the image of 'MicrosoftWindowsDesktop:Windows-10:win10-21h2-pro:19044.1706.220505' failed for an error '(ImageVersionDeprecated) VM Image from publisher: MicrosoftWindowsDesktop with - Offer: Windows-10, Sku: win10-21h2-pro, Version: 19044.1706.220505 is deprecated.
Code: ImageVersionDeprecated
Message: VM Image from publisher: MicrosoftWindowsDesktop with - Offer: Windows-10, Sku: win10-21h2-pro, Version: 19044.1706.220505 is deprecated.'. Configuring plan settings will be skipped" is the error message while creating a Windows 10 Pro VPS.

**Comment by kmille36** [comment]
Updated! Please see in [READ-THIS.txt](https://github.com/kmille36/Windows-11-VPS/blob/main/READ-THIS.txt) !
