### ISSUE TITLE
how to create linux vps

### ISSUE THREAD

**Issue by wcw1qqw** [kmille36/Windows-11-VPS#64]
i tried this https://docs.microsoft.com/en-us/cli/azure/azure-cli-vm-tutorial-1
but I didn't succeed
please help me
thanks

**Comment by kmille36** [comment]
What did u try?

**Comment by wcw1qqw** [comment]
> What did u try?

`resourcegroup=learn-056b9c25-e647-480e-863a-1a4491a16d10
name=1
az network vnet create \
  --name Net1 \
  --resource-group $resourcegroup \
  --address-prefixes 10.0.0.0/16 \
  --subnet-name SubNet1 \
  --subnet-prefixes 10.0.0.0/24

az vm create \
  --resource-group $resourcegroup \
  --name $name \
  --image UbuntuLTS \
  --vnet-name Net \
  --subnet SubNet \
  --generate-ssh-keys \
  --output json \
  --verbose `
But i dont know how to create with 7gRAM
