### ISSUE TITLE
Please add windows 11 pro and windows 10 pro i dont like enterprise version

### ISSUE THREAD

**Issue by sadiPod** [kmille36/Windows-11-VPS#7]
Please add windows 11 pro and windows 10 pro i dont like enterprise version

**Comment by kmille36** [comment]
Ok, that sound good.

**Comment by kmille36** [comment]
I will testing and adding it.

**Comment by sadiPod** [comment]
> I will test and add it.

Any updates???

**Comment by sadiPod** [comment]
> I will test and add it.

update please please

**Comment by sadiPod** [comment]
Any Updates??????

**Comment by kmille36** [comment]
Sorry for late, I will get that done tonight.

**Comment by sadiPod** [comment]
Thanks for updates

**Comment by sadiPod** [comment]
Is this updated?????

**Comment by sadiPod** [comment]
Still On Windows 11 & 10 Enterprices Please ASAP........

**Comment by kmille36** [comment]
Added !!! Please check!
