### ISSUE TITLE
add france central location in the script

### ISSUE THREAD

**Issue by MaazDev** [kmille36/Windows-11-VPS#78]
Hello , thanks for your script is it possible that you add france central as a location for the RDP ?

**Comment by kmille36** [comment]
Sorry, cant support.

**Comment by MaazDev** [comment]
I'm able to select it and create it using the recource learn group with the azure portal

**Comment by MaazDev** [comment]
can you explain me pls why it's not possible to add this location ? I try to do it manually but got no internet

**Comment by kmille36** [comment]
I will not explain about my source code. Sorry. But I'm the developer of this script, and I tried but could not make it work.

**Comment by kmille36** [comment]
> can you explain me pls why it's not possible to add this location ? I try to do it manually but got no internet

Of course, by default VM does not have internet access because ms learn dev team blocked it. Only my script can bypassing this.

**Comment by scatcat5isdead** [comment]
woah must be good scripter if he could bypass nointernet

**Comment by kmille36** [comment]
> woah must be good scripter if he could bypass nointernet

Yes, my script does this very well and good news is sandbox increase time 1hr into 2hrs.

**Comment by scatcat5isdead** [comment]
yea
