### ISSUE TITLE
hi can you add windows 7 if possible?

### ISSUE THREAD

**Issue by NineTailedCommanderSnake** [kmille36/Windows-11-VPS#8]
hi can you add windows 7 if possible?

**Comment by kmille36** [comment]
Too hard. Seem it not available in sandbox subscription.

**Comment by NineTailedCommanderSnake** [comment]
can you add like other windows builds like 10 home or like other versions of windows?

**Comment by kmille36** [comment]
No windows 10 Home

**Comment by NineTailedCommanderSnake** [comment]
alr
