### ISSUE TITLE
Azure Lab Services

### ISSUE THREAD

**Issue by scatcat5isdead** [kmille36/Windows-11-VPS#84]
They are gone so going to the link will bring you to a error page. Just use the ms learn method and go deploy was up after it was removed and will update if it's back.

**Comment by kmille36** [comment]
Thanks, hope godeploy demo lab is coming back soon

**Comment by scatcat5isdead** [comment]
it was back for the span of a week after you removed it for the Azure Lab Services method

**Comment by scatcat5isdead** [comment]
yeah its back
