### ISSUE TITLE
ubuntu

### ISSUE THREAD

**Issue by Yaselie** [kmille36/Windows-11-VPS#86]
Hello
Do you have a method to get Ubuntu server in the same way?

**Comment by kmille36** [comment]
what your purposes? Can i know?

**Comment by Yaselie** [comment]
Personal software testing
It cannot be done in Google Cloud and Colab due to closed ports or restrictions, it must be a server

**Comment by kmille36** [comment]
Ms learn sandbox VM does not open all port.

**Comment by kmille36** [comment]
And why u not buy your own VM?

**Comment by Yaselie** [comment]
yes sandbox dont open all port
and last way buy vm

**Comment by Yaselie** [comment]
yes sandbox dont open all port
and last way buy vm
