### ISSUE TITLE
roblox ain't working

### ISSUE THREAD

**Issue by Shriy1556k** [kmille36/Windows-11-VPS#90]
![image](https://user-images.githubusercontent.com/81312355/198860977-10997a0a-9fa9-4d22-ac50-8a42e9c7f8c3.png)
help

**Comment by Shriy1556k** [comment]
UDP 49152 - 65535 can you allll open these ports?

**Comment by Shriy1556k** [comment]
it's for roblox

**Comment by kmille36** [comment]
I can't open these port.

**Comment by Shriy1556k** [comment]
why

**Comment by kmille36** [comment]
it due sandbox policy, i can't change that.
