### ISSUE TITLE
No such file or directory Error

### ISSUE THREAD

**Issue by usernamefound** [kmille36/Windows-11-VPS#91]
Hey there, when I try to the command "curl -skLO bit.do/azurewinvmplus ; chmod +x azurewinvmplus ; ./azurewinvmplus", it says:
"chmod: cannot access 'azurewinvmplus': No such file or directory
bash: ./azurewinvmplus: No such file or directory"

Any solutions?
thanks.

**Comment by kmille36** [comment]
bit.do is temporary down, use is.gd instead.

**Comment by usernamefound** [comment]
Thanks for the prompt response. gd.is working perfectly!
