### ISSUE TITLE
Can I change working hour?

### ISSUE THREAD

**Issue by conep78** [kmille36/Windows-11-VPS#93]
now vps is only available for 2 hour and I need more time according to work.

**Comment by kmille36** [comment]
Create your own azure account then u can use it for u work

**Comment by kmille36** [comment]
Free VM service for everyone, not just for u.

**Comment by kmille36** [comment]
I see your github profile just recently joined and no repository? What are project your working on?? Or u just need more time for abuse free VM for your puporse?
