### ISSUE TITLE
increase of rdp to 12 hrs

### ISSUE THREAD

**Issue by Shriy1556k** [kmille36/Windows-11-VPS#96]
I am coding my discord bot i can't make a rdp every 2 hrs so can you pls increase it to 12hrs

**Comment by kmille36** [comment]
???

**Comment by kmille36** [comment]
Not free? if u want rdp with longer time, contact me to buy.

**Comment by Shriy1556k** [comment]
how much

**Comment by Shriy1556k** [comment]
and how can i contact you

**Comment by kmille36** [comment]
fb.com/thuong.hai.581 ?

**Comment by Shriy1556k** [comment]
i am not in facebook

**Comment by Shriy1556k** [comment]
you on discord

**Comment by Shriy1556k** [comment]
closed by mistake

**Comment by kmille36** [comment]
thuonghai2711#7681 discord

**Comment by Shriy1556k** [comment]
I sent you frnd request
